console:
  out:
    appendEolIfNecessary: true
    alwaysFlush: true

usb:
  # Specify the scan interval. I.e., how often we will scan
  # for new USB devices. The format is Duration, which sucks
  # so may perhaps redo this... See Duration.parse in the javadocs
  scanInterval: PT10S
  whiteList:
    # Quectel
    - 2c7c
    # Sierra Wireless
    - 1199

modem:

  # Whenever we need to reset the modem we will execute the following
  # set success commands in the order given.
  # Checkout the FSM diagrams for when this occurs but in short, we will
  # reset the modem upon attaching to it the first time and whenever
  # we end up in a unknown/bad state and try to get the modem back to a working
  # order.
  resetCommands:
    - ATZ

  # Need to figure out how to specify chars in yaml...
  # s3: '\r'
  # s4: '\n'
  verboseResponseFormat: true

  # the output stream towards the modem. I.e., this is the stream
  # we write to in order to write commands to the modem
  out:
    appendEolIfNecessary: false # the S3 & S4 character settings dictates this
    alwaysFlush: true

# Configuration for each command in the system. The main
# thing here is that each command may take a different
# amount of time to complete but we still need to make
# sure that we eventually will abort a command. E.g.
# AT+COPS=? may take up to a minute to execute so we
# must allow for that but ATI should return pretty much
# right away. As such, we need to be able to configure the
# expected timeout for all the different commands
commands:
  # Unless otherwise specified, we will maximum wait for
  # this many milliseconds before we assume we failed to
  # execute the command.
  defaultTimeoutMs: 1000

hektor:
  dispatchers:
    my-dispatcher:
      executor: worker-thread-executor
      workerThreadExecutor:
        noOfWorkers: 4
      throughput: 75
